name: Build

on:
    push:
        branches: [main]
    pull_request:
    release:
        types: [created]
    schedule:
        -   cron: '0 0 * * *'

jobs:
    build:
        name: Build
        strategy:
            matrix:
                gradle-version: [ current, 5.6.4 ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Determine the version
              # Updates the build version to the tag if it's a release.
              # Otherwise updates the build version to latest tag with the branch name as a suffix (i.e. 1.0.0-feature-upload).
              run: |
                LAST_VERSION=$(git describe --abbrev=0 --tags 2>/dev/null || echo 0.0.0)
                VERSION_SUFFIX=$(echo ${{ github.head_ref }} | sed -e 's/^refs\///' -e 's/[^0-9a-zA-Z\-_]/-/g')
                BUILD_VERSION=$([[ "${{ github.event_name }}" == "release" ]] && echo $LAST_VERSION || echo "$LAST_VERSION-$VERSION_SUFFIX")
                sed -i'' -e "/^version=/s/=.*/=$BUILD_VERSION/" gradle.properties
                echo $BUILD_VERSION
                echo "::set-env name=BUILD_VERSION::$BUILD_VERSION"
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Configure gradle ${{ matrix.gradle-version }}
              run: sed -i.bkp -e 's/\(distributionUrl=.*gradle\)-[0-9]*\.[0-9]*\(\.[0-9]*\)\{0,1\}\(.*\)/\1-${{ matrix.gradle-version }}\3/' gradle/wrapper/gradle-wrapper.properties
              if: ${{ matrix.gradle-version != 'current' }}
            - name: Build
              run: ./gradlew build --stacktrace
            - name: Upload artifacs
              if: ${{ matrix.gradle-version == 'current' }}
              uses: actions/upload-artifact@v2
              with:
                name: jars
                path: build/libs/*.jar
